### ISSUE TITLE
Support User access token to create the issue

### ISSUE THREAD

**Issue by sshniro** [zaproxy/action-baseline#18] opened 2020-04-21 12:21 UTC
Currently, the action checks for the latest bot comment to find the latest runner ID. 
But users can also use their personal access token to create the issues. Due to this, the action ends of creating new issues per scan, as it cannot find a matching comment by the bot.

**Comment by Den4200** [comment] 2023-06-30 14:09
Any update on this? The current behavior now is that 

I found the culprit to be these two lines hardcoded to check for the GitHub Actions bot.

https://github.com/zaproxy/action-baseline/blob/ff22721137aabfd0ed356ece585fc6747f4e527c/dist/index.js#L8088

https://github.com/zaproxy/action-baseline/blob/ff22721137aabfd0ed356ece585fc6747f4e527c/dist/index.js#L8111

**Comment by thc202** [comment] 2023-06-30 14:41
Closing as duplicate of #17.

**Closed by thc202** 2023-06-30 14:41 UTC
Labels: enhancement
