### ISSUE TITLE
Nodejs 12 deprecated, upgrade to Nodejs 16. 

### ISSUE THREAD

**Issue by derekmurawsky** [zaproxy/action-baseline#97] opened 2023-04-06 18:09 UTC
Scanning with the github action, I got the following annotation. 

Scan the target with ZAP Baseline X 

Node.js 12 actions are deprecated. Please update the following actions to use Node.js 16: zaproxy/action-baseline@v0.7.0. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/.

Please upgrade this action to the newer version.

**Comment by kingthorin** [comment] 2023-04-06 18:15
Please contact GitHub, they're displaying that annotation on basically every action run. It has nothing to do with this action. I see it all over the place all the time.

Duplicate of zaproxy/action-baseline#83

![image](https://user-images.githubusercontent.com/7570458/230461706-8ba9d709-097f-4c7f-a571-a07e4b701810.png)

**Closed by kingthorin** 2023-04-06 18:15 UTC

**Comment by derekmurawsky** [comment] 2023-04-06 18:54
Maybe I'm missing something, but those changes were made 6 months ago, but the last release was 0.7.0, which was released on May 23, 2022, which is 9 months ago. Perhaps the new release wasn't cut, so there isn't a newer action available for us to reference?

**Comment by thc202** [comment] 2023-04-06 18:57
Actions can be used without a tag or release, you can use the commit or the branch (commit is safer).

**Comment by kingthorin** [comment] 2023-04-06 19:03
That's fair, thanks for following up.

**Comment by thc202** [comment] 2023-04-06 19:07
Which docs?

**Comment by kingthorin** [comment] 2023-04-06 19:11
I'm guessing just the repo README

**Comment by thc202** [comment] 2023-04-06 19:12
In the readme it's an example usage.

**Comment by kingthorin** [comment] 2023-04-06 19:16
Agreed 😀
