### ISSUE TITLE
Octokit problem

### ISSUE THREAD

**Issue by njox** [zaproxy/action-baseline#34] opened 2020-06-30 13:43 UTC
Hi, when I trigger module I got this:

```console
FAIL-NEW: 0	FAIL-INPROG: 0	WARN-NEW: 8	WARN-INPROG: 0	INFO: 0	IGNORE: 0	PASS: 43
[@octokit/rest] `const Octokit = require("@octokit/rest")` is deprecated. Use `const { Octokit } = require("@octokit/rest")` instead
##[error]The ZAP Baseline scan has failed, starting to analyze the alerts. err: Error: The process '/usr/bin/docker' failed with exit code 2
Alerts present in the current report: true
Process completed successfully and a new issue #2 has been created for the ZAP Scan.
```

It seems that the importing library @octokit/rest is wrong.

**Comment by thc202** [comment] 2020-06-30 13:58
The warning is caused by a dependency (`@actions/github`) not this action, we'll have to update it.

**Comment by njox** [comment] 2020-06-30 14:07
Thanks for your fast response. When will come a new update?

**Comment by kingthorin** [comment] 2020-06-30 14:28
It seems to be behaving as expected. It exited code 2 because you have new warnings.

What's the issue you're trying to report?

**Comment by thc202** [comment] 2020-06-30 14:32
> When will come a new update?

There's no ETA for the update/release.

> What's the issue you're trying to report?

I think the warning, despite everything working as expected better to update.

**Comment by njox** [comment] 2020-06-30 14:48
I can't share repository and log because it's private and has copyright. But the workflow is:

1. Create a deployment package for AWS EBS
2. Upload package to AWS S3 Budget
3. Trigger application update from AWS S3 Bucket
4. Perform ZAP scan (basic configuration - using the only _target_ in _with_ property)

On 4. step I got a warning/issue which forces action to fail but it will create a report file.

Thanks

**Comment by thc202** [comment] 2020-06-30 14:53
The Octokit warning is not the cause why the build fails but the warnings/alerts ZAP found `WARN-NEW: 8`.

**Comment by richAtreides** [comment] 2020-07-07 10:58
To be clear why would it fail if there is a warning. Is this just a hacky way of giving alerts? How do you change the verbosity so that it fails on actual issues only?

**Comment by thc202** [comment] 2020-07-07 11:12
If with "it" you are referring to the action itself, that's #31.

**Comment by richAtreides** [comment] 2020-07-08 10:08
> If with "it" you are referring to the action itself, that's #31.

@thc202 that issue perfectly covers my concern. Is there a way to stop this just failing if it finds any warnings but instead configure it? Or is that to be built?

**Comment by psiinon** [comment] 2020-07-10 08:25
You can just specify a rules file with the relevant rules to IGNORE instead of WARN.

**Comment by njox** [comment] 2020-07-30 13:22
Hi guys,

Just tried the new release v0.3.0 and got:

1. Basic configuration - `The ZAP Baseline scan has failed, starting to analyze the alerts. err: Error: The process '/usr/bin/docker' failed with exit code 2` .After that, I saw there is a new parameter `fail_action`.
2. Tried in `with` parameter the `fail_action` with the value true or false which will produce an error `Unexpected input(s) 'fail_action', valid inputs are ['token', 'target', 'rules_file_name', 'docker_name', 'cmd_options', 'issue_title']`

By default ZAP Docker container will fail that is alright, but can we add and set `fail_action` to false if we want to ignore warnings which will produce action to pass?

Thanks

**Comment by kingthorin** [comment] 2020-07-30 13:47
@njox the `fail_action` handling hasn't been released yet. You'd have to use the action based on commit id or wait for v0.4.0

**Comment by masonator** [comment] 2020-08-20 13:22
Having the same problem and tried the various workarounds but didn't have any luck. Is there an ETA for v0.4.0 currently? Would love to start using the action in production, but at the moment it fails our builds.

**Comment by thc202** [comment] 2020-10-16 10:30
For the record, the new version is now available.

**Comment by njox** [comment] 2020-10-16 11:32
Currently, I can't check the new version, but someone can test it, and if everything seems to be ok then the issue can be closed.

Thanks

**Comment by richAtreides** [comment] 2020-10-16 11:34
> Currently, I can't check the new version, but someone can test it, and if everything seems to be ok then the issue can be closed.
> 
> 
> 
> Thanks

I'll be online in about an hour and can test it to close the issue.

**Comment by thc202** [comment] 2020-10-16 11:42
The issue should be kept open as the deprecation was not yet addressed.

**Comment by samrobinson123** [comment] 2020-11-09 16:02
Issue still seems to be reproducing on v0.4.0, albeit with an exit code 3 instead of 2.

`Error: failed to scan the target: Error: The process '/usr/bin/docker' failed with exit code 3`

**Comment by kingthorin** [comment] 2020-11-09 16:12
@samrobinson123 please provide a link to your config/use.

**Comment by samrobinson123** [comment] 2020-11-09 16:18
Workflow is part of a private repository and so i'll put it here. 

Please note, i've removed the target website in this example.


on: [push]

jobs:
      zap_scan:
           runs-on: ubuntu-latest
           name: Scan the web application
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: main
      - name: ZAP Scan
        uses: zaproxy/action-baseline@v0.4.0
        with:
         target: ‘My target'

**Comment by kingthorin** [comment] 2020-11-09 16:29
Thanks.

You mentioned your use exited with code 3, that's not related to Alerts, you seem to have some other failure.
Ref: https://github.com/zaproxy/zaproxy/blob/efb404d38280dc9ecf8f88c9b0c658385861bdcf/docker/zap-baseline.py#L31-L35

**Comment by kingthorin** [comment] 2020-11-09 17:14
> 
> 
> The issue should be kept open as the deprecation was not yet addressed.

@sshniro is addressing the deprecation warning as simple as updating our dependencies?

**Comment by thc202** [comment] 2020-11-09 17:24
The update would address the warning (https://github.com/actions/toolkit/issues/333), not sure if it's as simple as, it's a major update (from 1.x to 2.x).

**Comment by sshniro** [comment] 2020-12-06 12:59
Hi @kingthorin , I will test this scenario in the coming weekend and will send a PR.

**Comment by jasikpark** [comment] 2020-12-09 20:08
I am getting a similar error: https://github.com/jasikpark/jasik-xyz/runs/1521221382?check_suite_focus=true

**Comment by rubaljain** [comment] 2021-09-05 20:08
Was this issue resolved? Do we have configurable fail_action to pass the workflow even if we observe the findings?

**Comment by thc202** [comment] 2021-09-06 10:15
The issue #31 was resolved and released in the latest version.

**Comment by hakrishi** [comment] 2023-02-01 11:29
Hey, did anyone find a fix for the Otokit dependancy issue? I'm running zaproxy/action-baseline@v0.7.0. Thanks

**Comment by thc202** [comment] 2023-06-30 11:25
This no longer happens with the latest version (v0.8.0).

**Closed by thc202** 2023-06-30 11:25 UTC
